version: "3.7"
services:
  hermes-account-1:
    image: hermes-account:0.1.1
    container_name: hermes-account01
    ports:
      - "10010:8080"
    volumes:
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
    networks:
      hermes-net:
  hermes-account-2:
    image: hermes-account:0.1.1
    container_name: hermes-account02
    ports:
      - "10011:8080"
    volumes:
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
    networks:
      hermes-net:
networks:
  hermes-net:
    name: hermes-network
