server:
  port: 10010

spring:
  application:
    name: hermes-account
  jpa:
    database: mysql
  datasource:
    url: jdbc:mysql://192.168.1.121:3306/hermes
    username: root
    password: 123456
  redis:
    host: 192.168.1.121
    port: 6379
    database: 0
    timeout: 3000
  rabbitmq:
    host: 192.168.1.121
    port: 5672
    username: admin
    password: admin
  cloud:
    consul:
      host: 192.168.1.121
      port: 8500
      discovery:
        health-check-interval: 10s
        health-check-path: /actuator/health
        enabled: true
        register: true
        service-name: ${spring.application.name}
        prefer-ip-address: true
        instance-id: ${spring.application.name}-${spring.cloud.client.ip-address}:${server.port}